config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/destroy'
  get 'tasks/today'
  get 'projects/new'
  get 'projects/create'
  get 'projects/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :sessions, only: [:new, :create, :destroy]


    get 'static_pages/index'
    get 'signin' => 'sessions#new'
    get 'signup' => 'users#new'

    get '/task/:id/todo', to: 'tasks#make_todo'
      get '/task/:id/today', to: 'tasks#make_today'
        get '/task/:id/in_process', to: 'tasks#make_in_process'
          get '/task/:id/done', to: 'tasks#make_done'


  get '/tasks/notifications', to: 'tasks#notifications'

  post '/tasks/makealltodo', to: 'tasks#makealltodo'
  post '/tasks/makealltoday', to: 'tasks#makealltoday'

    delete '/signout', to: 'sessions#destroy'

    root 'static_pages#index'

    resources :projects, only: [:create, :destroy, :index, :update, :show]
    resources :points, only: [:index]
    resources :users, only: [:show, :create]
    resources :tasks, only: [:create, :destroy, :index, :show, :edit, :update] do
      get :today
    end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_many :points, dependent: :destroy
  enum task_state: {
      todo: 0,
      today: 1,
      in_process: 2,
      done: 3
  }


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def create
    @task = current_user.projects.find(params[:project_id]).tasks.create(task_params)
  end

  def destroy
    @task = current_user.tasks.find(params[:id]).destroy
  end

  def today

    @today_count = current_user.tasks.today.count
    @today_done = current_user.tasks.done.where('today_at > ? AND today_at < ?', Date.today - 1.day, Date.today + 1.day).count

  end

  def makealltoday
    @type = params[:type]
    params[:ids].each do |id|
      @task = current_user.tasks.find(id)
      @task.today!
      @task.update_attribute(:today_at, Date.today)
      @task.points.destroy_all
    end
  end

  def makealltodo
    @type = params[:type]
    params[:ids].each do |id|
      @task = current_user.tasks.find(id)
      if @task.today?
        @task.update_attribute(:today_at, Date.today)
      end
      @task.todo!
      @task.points.destroy_all
    end
  end

  def make_todo
    @task = current_user.tasks.find(params[:id])
    if @task.today?
      @task.update_attribute(:today_at, Date.today)
    end
    @task.todo!
    @task.points.destroy_all

    @today_count = current_user.tasks.today.count
    @today_done = current_user.tasks.done.where('today_at > ? AND today_at < ?', Date.today - 1.day, Date.today + 1.day).count
  end

  def make_today
    @task = current_user.tasks.find(params[:id])
    @task.today!
    @task.update_attribute(:today_at, Date.today)
    @task.points.destroy_all
  end

  def make_in_process
    @task = current_user.tasks.find(params[:id])
    @task.in_process!
    @task.points.destroy_all
  end

  def make_done
    @task = current_user.tasks.find(params[:id])
    @task.done!
    @task.update_attribute(:today_at, Date.today)

    @today_count = current_user.tasks.today.count
    @today_done = current_user.tasks.done.where('today_at > ? AND today_at < ?', Date.today - 1.day, Date.today + 1.day).count

    if current_user.tasks.done.count == 1
      @task.points.create(quantity: 1, user: current_user)
      @text = "Поздравляем! Ты закрыл свою первую задачу! Лови бонусные баллы"
      @points = 1;
    end
    if current_user.tasks.done.count == 25
      @task.points.create(quantity: 10, user: current_user)
      @text = "Поздравляем! Ты закрыл 25 новых задач! Лови бонусные баллы"
      @points = 10;
    end
    if current_user.tasks.done.count == 50
      @task.points.create(quantity: 20, user: current_user)
      @text = "Поздравляем! Ты закрыл 50 новых задач! Лови бонусные баллы"
      @points = 20;
    end

    if current_user.tasks.done.count == 75
      @task.points.create(quantity: 30, user: current_user)
      @text = "Поздравляем! Ты закрыл 75 новых задач! Лови бонусные баллы"
      @points = 30;
    end
    if current_user.tasks.done.count == 100
      @task.points.create(quantity: 40, user: current_user)
      @text = "Поздравляем! Ты закрыл 100 новых задач! Лови бонусные баллы"
      @points = 40;
    end
  end

  def notifications
    @three_day_tasks = current_user.tasks.where('deadline > ? AND deadline < ?', Date.today + 2.days, Date.today + 4.days)
    @one_day_tasks = current_user.tasks.where('deadline > ? AND deadline < ?', Date.today, Date.today + 2.days)
    @week_tasks = current_user.tasks.where('deadline > ? AND deadline < ?', Date.today + 6.days, Date.today + 8.days)

    @week = []
    if current_user.activity < Date.today - 4.days && current_user.tasks.today
      @week = current_user.tasks.today
    end

    @day = current_user.tasks.where('today_at < ? AND today_at > ?', Date.today, Date.today - 2.days)

    if @three_day_tasks.any?
      @three_day_tasks_titles = @three_day_tasks.pluck(:title).join(', ')
    end

    if @one_day_tasks.any?
      @one_day_tasks_titles = @one_day_tasks.pluck(:title).join(', ')
    end

    if @week_tasks.any?
      @week_tasks_titles = @week_tasks.pluck(:title).join(', ')
    end
    render :notifications
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    @task.update(task_params)
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end



  private
  def task_params
    params.require(:task).permit(:title, :description, :task_state, :deadline)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit_task_actions.html.erb
<div style="padding-left: 32px;">
  <button onclick="updateTask(<%=task.id%>)" class=" btn-flat waves-effect waves-dark" style="color: #171717;" type="submit" name="action">
    Сохранить изменения
    </button>
</div>

<script>

  function updateTask(){
    var update_task_title = $('#edit-task-title').val();
    var update_task_description = $('#edit-task-description').val();
    var update_task_deadline = $('#edit-task-deadline').val();

    $.ajax({
          url: '<%= task_path(task) %>', type: 'put', data: {project_id: '<%=task.project.id%>', task: {title: update_task_title, description: update_task_description,  deadline: update_task_deadline}}
        })
        .done(function(){
          $('#view-task-<%=task.id%>').remove()
        });
    }

</script>

app/views/tasks/_edit_task_data.html.erb
<div class="input-field" style="">
         <input id="edit-task-title" type="text" value="<%=@task.title%>" class="validate">
         <label for="edit-task-title">Введите название задачи</label>
       </div>
       <div class="input-field" style="">
                <input active id="edit-task-description" type="text" value="<%=@task.description%>" class="active">
                <label for="edit-task-description">Введите описание задачи</label>
              </div>
              <div class="input-field" style="">
                       <input id="edit-task-deadline" type="text" value="<%=@task.deadline? ? @task.deadline.strftime("%b %d, %Y") : ''%>" class="datepicker">
                       <label for="edit-task-deadline" class="active">Выберите дедлайн</label>
                     </div>
                     <script>

                     $(document).ready(function(){
                         $('.datepicker').datepicker();
                          var picker = M.Datepicker.getInstance(document.getElementById('edit-task-deadline'))
                          picker.setDate('<%=@task.deadline%>');
                          M.updateTextFields();
                       });



                     </script>

app/views/tasks/_new_task.html.erb
<div id="new-task-form" style="position: fixed; z-index: 9; display: flex; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0, 0, 0, 0.2); align-items: center;
    justify-content: center;">

  <div style="z-index: 1; border-radius: 32px; height: 515px; width:996px; background-color: white;  position: absolute; ">

  <div style="display:flex; padding: 32px; aling-items: center; border-bottom: 1px solid #c5c5c5;">
    <div style="flex-grow: 1; font-weight: 600; font-size: 18px; align-self: center;">Новая задача</div>
     <div>
       <a onclick="hideForm()" class="waves-effect waves-yellow btn-flat"><i class="material-icons">close</i></a>
     </div>
  </div>

  <div style="font-weight: 600; font-size: 24px; padding: 32px; ">
    Название задачи
  </div>

<div style="padding-left: 32px; padding-right: 32px;  ">
    <div class="input-field" style="">
             <input id="task-title" type="text" >
             <label for="task-title">Введите название задачи</label>
           </div>
           <div class="input-field" style="">
                    <input id="task-description" type="text">
                    <label for="task-description">Введите описание задачи</label>
                  </div>
                  <div class="input-field" style="">
                           <input id="task-deadline" type="text" class="datepicker">
                           <label for="task-deadline" class="active">Выберите дедлайн</label>
                         </div>

                         <input id="task-state" type="text" style="display: none;">
</div>


<div style="padding-left: 32px;">
  <button onclick="createTask()" class="btn waves-effect waves-light yellow" style="color: #171717;" type="submit" name="action">
    Создать
    </button>

  <a onclick="hideForm()" class="waves-effect waves-yellow btn-flat">Отмена</a>
</div>
  </div>
</div>


<script>

hideForm();

function hideForm(){
$('#new-task-form').hide();
  $('#task-title').val('');
  $('#task-description').val('');
  $('#task-deadline').val('');
  $('#task-state').val('');
  M.updateTextFields();
}

$(document).ready(function(){
    $('.datepicker').datepicker();
  });

  function createTask(){
    var title = $('#task-title').val();
    var description = $('#task-description').val();
    var deadline = $('#task-deadline').val();
    var task_state = $('#task-state').val();

    $.ajax({
          url: '<%= tasks_path %>', type: 'post', data: {project_id: '<%=@project.id%>', task: {title: title, description: description, task_state: task_state, deadline: deadline}}
        })
        .done(function(){
          $('#task-title').val('');
          $('#task-description').val('');
          $('#task-deadline').val('');
          $('#task-state').val('');
            M.updateTextFields();
        })
    }

</script>

app/views/tasks/_task_data.html.erb
<div class="task-data-title">
  <%=task.title%>
</div>
<div class="task-data-project-title">
  <%=task.project.title%>
</div>
<div class="task-data-description" style="">
  <%=task.description%>
</div>
<% if !task.deadline.nil?%>
  <div class="task-data-deadline" style=""><i style="font-size: 10px; margin-right: 8px;" class="material-icons">schedule</i><%=task.deadline.strftime("%b %d, %Y")%></div>
<% end %>

app/views/tasks/_tasks.html.erb
<div class="row" id="" style="margin-top: 32px;">

<div class=" col m12 s12 l12 xl12">
  <div class="col m3" style="font-size: 18px;">
      Сделать
  </div>
  <div class="col m3" style="font-size: 18px;">
      Сегодня
  </div>
  <div class="col m3" style="font-size: 18px;">
      В процессе
  </div>
  <div class="col m3" style="font-size: 18px;">
      Готово
  </div>

</div>
<div class=" col m12 s12 l12 xl12">
  <% if @project %>
    <div class="col m3 s3">
        <a style="z-index: 0;" onclick="showNewTaskForm('<%=Task.task_states.keys.first%>')" id="" class="waves-effect waves-yellow btn-flat  btn-flat-grey">Новая задача <i class="material-icons left">add</i></a>
    </div>
  <% end %>

<% if @project %>
  <div class="col m3 s3">
    <a style="z-index: 0;" onclick="showNewTaskForm('<%=Task.task_states.keys.second%>')" id="" class="waves-effect waves-yellow btn-flat  btn-flat-grey">Новая задача <i class="material-icons left">add</i></a>
  </div>
<% end %>

<% if @project %>
  <div class="col m3 s3">
    <a style="z-index: 0;" onclick="showNewTaskForm('<%=Task.task_states.keys.third%>')" id="" class="waves-effect waves-yellow btn-flat btn-flat-grey">Новая задача <i class="material-icons left">add</i></a>
  </div>
<% end %>


</div>

<div class=" col m12 s12 l12 xl12">

<div class="col m3 s3" style="display: flex; flex-direction: column;">
  <div style="margin-top: 16px;" id="todo-tasks">
    <%= render :partial => "tasks/task", :collection => @project ? @project.tasks.all.todo.order('created_at DESC') : current_user.tasks.all.todo.order('created_at DESC'), :as => :task %>
  </div>
</div>

<div class="col m3 s3">
  <div style="margin-top: 16px;" id = "today-tasks" ondragover="allowDrop(event)" ondrop="drop(event)">
    <%= render :partial => "tasks/task", :collection =>  @project ? @project.tasks.all.today.order('created_at DESC') : current_user.tasks.all.today.order('created_at DESC'), :as => :task %>
  </div>
</div>

<div class="col m3 s3">
  <div style="margin-top: 16px;" id = "in_process-tasks">
    <%= render :partial => "tasks/task", :collection =>  @project ? @project.tasks.all.in_process.order('created_at DESC') : current_user.tasks.all.in_process.order('created_at DESC'), :as => :task %>
  </div>
</div>

<div class="col m3 s3">
  <div style="margin-top: 16px;" id = "done-tasks">
    <%= render :partial => "tasks/task", :collection => @project ?  @project.tasks.all.done.order('created_at DESC') : current_user.tasks.all.done.order('created_at DESC'), :as => :task %>
  </div>
</div>
</div>

<script type="text/javascript">
  function allowDrop(ev) {
    ev.preventDefault();
  }

  function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
  }

  function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    ev.target.appendChild(document.getElementById(data));
}

function showNewTaskForm(type) {
$('#new-task-form').show()
$('#task-state').val(type)
}
</script>

</div>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.js.erb
$('#task-data').html('<%=escape_javascript(render 'tasks/edit_task_data', task: @task)%>')
$('#task-actions').html('<%=escape_javascript(render 'tasks/edit_task_actions', task: @task)%>')

app/views/tasks/index.html.erb
<div class="container">
  <%if signed_in_user?%>
      <%= render 'tasks/tasks', project: false%>
    <%end%>
</div>

app/views/tasks/make_in_process.js.erb
$('#task-<%=@task.id%>').remove()
$('#view-task-<%=@task.id%>').remove()
$('#in_process-tasks').prepend("<%=escape_javascript(render 'tasks/task', task: @task)%>")

app/views/tasks/make_todo.js.erb
$('#task-<%=@task.id%>').remove()
$('#view-task-<%=@task.id%>').remove()
$('#todo-tasks').prepend("<%= escape_javascript(render 'tasks/task', task: @task)%>")
$('#today-task-<%=@task.id%>').remove()


tasks_done = <%=@today_done%>
tasks_todo = <%=@today_count%>

app/views/tasks/makealltoday.js.erb
$('#notification-<%=@type%>').remove()
<% @ids.each do |id| %>
<%@task = current_user.tasks.find(id)%>
  $('#task-<%=@task.id%>').remove()
  $('#today-tasks').prepend("<%=escape_javascript(render 'tasks/task', task: @task)%>")
<%end%>

app/views/tasks/notifications.js.erb
<%if @three_day_tasks.any? %>
$('body').append("<%=escape_javascript(render 'tasks/notification',  type: 3)%>")
<%end%>
<%if @one_day_tasks.any? %>
$('body').append("<%=escape_javascript(render 'tasks/notification',  type: 1)%>")
<%end%>
<%if @week_tasks.any? %>
$('body').append("<%=escape_javascript(render 'tasks/notification',  type: 7)%>")
<%end%>
<%if @week.any? %>
$('body').append("<%=escape_javascript(render 'tasks/notification',  type: 77)%>")
<%end%>
<%if @day.any? %>
$('body').append("<%=escape_javascript(render 'tasks/notification',  type: 71)%>")
<%end%>

app/views/tasks/today.html.erb
<div class="container">
  <div style="font-weight: bold;
font-size: 34px; line-height: 150%; padding-bottom: 32px; padding-top: 58px;">Задачи на сегодня</div>

<% if current_user.tasks.today.any? || current_user.tasks.done.where('today_at > ? AND today_at < ?', Date.today - 1.day, Date.today + 1.day).any? %>
<div class="row" style="display: flex; flex-direction: row">

  <div class="col m7"  id="today-tasks" style="display: flex; flex-direction: column;">
    <%= render :partial => 'tasks/today_task', :collection => current_user.tasks.today.order('created_at DESC'), :as => :task %>
    <% if !current_user.tasks.today.any? %>
      <div style="font-size: 24px; color: #333333; margin-bottom: 16px;"> Круто! Ты закрыл все задачи на сегодня! </div>
    <% end %>
      <div id="today-done-tasks" style="display: flex; opacity: 80%; flex-direction: column;">
        <%= render :partial => 'tasks/today_task', :collection => current_user.tasks.done.where('today_at > ? AND today_at < ?', Date.today - 1.day, Date.today + 1.day).order('created_at DESC'), :as => :task %>
      </div>
  </div>


  <div class="col m5" id="stats-bar" style="display: flex; margin-left: 24px; font-size: 24px;">
     <div id="donutchart" style="width: 900px; height: 500px;"></div>
  </div>

  </div>
<% else %>
  <img src="<%=image_url('today_placeholder.png')%>">
  <div style="max-width: 640px; font-size: 24px;">
      Упс! У тебя еще нет запланированных задач на сегодняшний день, перейди в проект и перенеси задачу в колонку “сегодня”.
  </div>
<% end %>
</div>

   <script type="text/javascript">

     var tasks_done = <%=@today_done%>;
     var tasks_todo = <%=@today_count%>;

     $(document).on('turbolinks:load', function() {
       google.charts.load("current", {packages:["corechart"]});
       google.charts.setOnLoadCallback(drawChart);

     });


     function taskUpdateTypeToday(id, type) {

     var url = '/task/' + id + '/' + type;

       $.ajax({
             url: url, type: 'get'
           })
           .done(function(){ drawChart() })
     }

     function drawChart() {
       var data = google.visualization.arrayToDataTable([
         ['Task', 'Hours per Day'],
         ['Выполнено',     tasks_done],
         ['Осталось',      tasks_todo]
       ]);

       var options = {
         title: 'Выполнено: ' + tasks_done + '/' + tasks_todo ,
         pieSliceText: 'none',
         pieHole: 0.7,
         legend: 'none',
         pieSliceText: 'value',
         titleTextStyle: { fontSize: 18,
                              bold: true },
        slices: {
            0: { color: '#6673FF' },
            1: { color: '#DADADA' }
          }
       };

       var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
       chart.draw(data, options);
     }



   </script>

app/views/tasks/update.js.erb
M.toast({html: 'Изменения сохранены', classes: 'rounded'})
$('#task-data-<%=@task.id%>').html('<%=escape_javascript(render 'tasks/task_card_data', task: @task)%>')