config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/destroy'
  get 'tasks/today'
  get 'projects/new'
  get 'projects/create'
  get 'projects/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :sessions, only: [:new, :create, :destroy]


    get 'static_pages/index'
    get 'signin' => 'sessions#new'
    get 'signup' => 'users#new'

    get '/task/:id/todo', to: 'tasks#make_todo'
      get '/task/:id/today', to: 'tasks#make_today'
        get '/task/:id/in_process', to: 'tasks#make_in_process'
          get '/task/:id/done', to: 'tasks#make_done'


  get '/tasks/notifications', to: 'tasks#notifications'

  post '/tasks/makealltodo', to: 'tasks#makealltodo'
  post '/tasks/makealltoday', to: 'tasks#makealltoday'

    delete '/signout', to: 'sessions#destroy'

    root 'static_pages#index'

    resources :projects, only: [:create, :destroy, :index, :update, :show]
    resources :points, only: [:index]
    resources :users, only: [:show, :create]
    resources :tasks, only: [:create, :destroy, :index, :show, :edit, :update] do
      get :today
    end

end

app/models/project.rb
class Project < ApplicationRecord

has_many :tasks, class_name: 'Task', dependent: :destroy
belongs_to :user





end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include SessionsHelper
  def index

  end

  def show
    @project = current_user.projects.find(params[:id])
  end

  def create
    @project = current_user.projects.new(project_params)

     if @project.save
       respond_to do |f|
         f.js
       end
     end
  end

  def destroy

    @project = current_user.projects.find(params[:id])
    @project.destroy

  end


  def update
    @project = current_user.projects.find(params[:id])
    @project.update(project_params)
  end


  private
  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_new_project.html.erb
<div id="new-project-form" style="position: fixed; display: flex; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0, 0, 0, 0.2); align-items: center;
    justify-content: center;">

  <div style="z-index: 1; border-radius: 32px; height: 515px; width:996px; background-color: white;  position: absolute; ">

  <div style="display:flex; padding: 32px; aling-items: center; border-bottom: 1px solid #c5c5c5;">
    <div style="flex-grow: 1; font-weight: 600; font-size: 18px; align-self: center;">Новый проект</div>
     <div>
       <a onclick="closeProjectForm()" class="waves-effect waves-yellow btn-flat"><i class="material-icons">close</i></a>
     </div>
  </div>

  <div style="font-weight: 600; font-size: 24px; padding: 32px; ">
    Название доски
  </div>

<div style="padding-left: 32px; padding-right: 32px;  ">
    <div class="input-field" style="">
             <input id="title" type="text">
             <label for="title">Введите название доски</label>
           </div>
</div>


<div style="padding-left: 32px;">
  <button onclick="createProject()" class="btn waves-effect waves-light yellow" style="color: #171717;" type="submit" name="action">
    Создать
    </button>

  <a onclick="closeProjectForm()" class="waves-effect waves-yellow btn-flat">Отмена</a>
</div>
  </div>
</div>


<script>
closeProjectForm();

  function closeProjectForm(){
    $('#new-project-form').hide();
    $('#title').val('');
    M.updateTextFields();
  }

  function createProject(){
    var title = $('#title').val();

    $.ajax({
          url: '<%= projects_path %>', type: 'post', data: {project: {title: title}}
        })
        .done(function(){ $('#title').val(""); M.updateTextFields(); })

    }


</script>

app/views/projects/_project.html.erb
<div  onmouseout="onOutProject(<%=project.id%>)" onmouseover="onHoverProject(<%=project.id%>)" id="project-<%=project.id%>" class="col s12 m6 l4 xl4" style="margin-bottom: 12px; padding: 0 6px; cursor: pointer;">
  <a  style="color: unset; flex-grow: 1;" href="<%=project_path(project)%>">
    <div  id="project-card-<%=project.id%>"  style=" background: white; border-radius: 8px;  height: 200px;  box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.12);">

      <div style="display: flex; flex-direction: column; height: 100%;">

        <div id="project-title-<%=project.id%>" style=" overflow: hidden; text-overflow: ellipsis;flex-grow: 4; word-break: break-word; padding: 32px; font-weight: 600; font-size: 24px; line-height: 32.4px;">
            <%= project.title%>
        </div>


        <div class="project-buttons" id="project-btns-<%=project.id%>" style="display: flex; justify-content:end; padding: 4px 4px 4px 4px;">
            <a style="z-index:0;" id="edit-project-<%=project.id%>" onclick="editProject(<%=project.id%>, '<%=project.title%>')" class="waves-effect waves-dark btn-flat btn-flat-small"><i class="material-icons">edit</i></a>
            <a style="z-index:0;" data-method="delete" data-remote="true" href="<%=project_path(project)%>" id="delete-project-<%=project.id%>" class="waves-effect waves-dark btn-flat btn-flat-small"><i class="material-icons">delete</i></a>
        </div>
    </div>


    </div>

</a>
</div>

<script type="text/javascript">

$('.project-buttons').hide();

</script>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/create.js.erb
$('#projects-container').prepend('<%= escape_javascript( render 'projects/project', project: @project)%>');
$('#new-project-form').hide();

app/views/projects/destroy.js.erb
$('#project-<%=@project.id%>').remove();

app/views/projects/index.html.erb
  <div class="container">
  <div style="font-size: 34px; font-weight: 600; margin-top: 60px; margin-bottom: 24px;">Мои проекты</div>

  <a style="z-index: 0;" id="new-project" onclick="$('#new-project-form').show();" class="waves-effect waves-yellow btn-flat">Новая доска<i class="material-icons left">add</i></a>

  <%= render 'new_project'%>


    <div class="row" id="projects-container" style="margin-top: 32px;">
      <% current_user.projects.all.order('created_at DESC').each do |project| %>
          <%= render 'projects/project', project: project %>
      <% end %>
    </div>
</div>


<div id="edit-project-form" style="position: fixed; display: flex; top: 0; left: 0; right: 0; bottom: 0; background: rgba(0, 0, 0, 0.2); align-items: center;
    justify-content: center;">

  <div style="z-index: 1; border-radius: 32px; height: 515px; width:996px; background-color: white;  position: absolute; ">

  <div style="display:flex; padding: 32px; aling-items: center; border-bottom: 1px solid #c5c5c5;">
    <div style="flex-grow: 1; font-weight: 600; font-size: 18px;">Проект</div>
     <div>
       <a onclick="$('#edit-project-form').hide()" id="new-project" class="waves-effect waves-yellow btn-flat"><i class="material-icons">close</i></a>
     </div>
  </div>

  <div style="font-weight: 600; font-size: 24px; padding: 32px; ">
    Название доски
  </div>

<div style="padding-left: 32px; padding-right: 32px;  ">
    <div class="input-field" style="">
             <input id="edit-title" type="text" value="" class="validate">
             <label class='active' for="edit-title">Название доски</label>
           </div>
</div>


<div style="padding-left: 32px;">
  <button onclick="saveProject()" class="btn waves-effect waves-light yellow" style="color: #171717;" type="submit" name="action">
    Сохранить изменения
    </button>

  <a id="new-project" class="waves-effect waves-yellow btn-flat">Отмена</a>
</div>
  </div>
</div>


<script>
$('#edit-project-form').hide();

var project_id;

  function editProject(id, title){
    project_id = id;
    $('#edit-title').val(title);
    $('#edit-project-form').show();
    M.updateTextFields();
  }

  function saveProject(){
    var editTitle = $('#edit-title').val();

    $.ajax({
          url: '/projects/' + project_id, type: 'put', data: {project: {title: editTitle}}
        })
        .done(function(){ $('#edit-project-form').hide(); })

    }


</script>

app/views/projects/show.html.erb
  <div class="container">

    <%= render 'tasks/new_task'%>
        <%= render 'tasks/tasks', project: @project%>
  </div>

app/views/projects/update.js.erb
$('#project-title-<%=@project.id%>').text('<%=@project.title%>')