config/routes.rb
Rails.application.routes.draw do

  get 'tasks/new'
  get 'tasks/create'
  get 'tasks/destroy'
  get 'tasks/today'
  get 'projects/new'
  get 'projects/create'
  get 'projects/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :sessions, only: [:new, :create, :destroy]


    get 'static_pages/index'
    get 'signin' => 'sessions#new'
    get 'signup' => 'users#new'

    get '/task/:id/todo', to: 'tasks#make_todo'
      get '/task/:id/today', to: 'tasks#make_today'
        get '/task/:id/in_process', to: 'tasks#make_in_process'
          get '/task/:id/done', to: 'tasks#make_done'


  get '/tasks/notifications', to: 'tasks#notifications'

  post '/tasks/makealltodo', to: 'tasks#makealltodo'
  post '/tasks/makealltoday', to: 'tasks#makealltoday'

    delete '/signout', to: 'sessions#destroy'

    root 'static_pages#index'

    resources :projects, only: [:create, :destroy, :index, :update, :show]
    resources :points, only: [:index]
    resources :users, only: [:show, :create]
    resources :tasks, only: [:create, :destroy, :index, :show, :edit, :update] do
      get :today
    end

end

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
<nav>
   <div class="nav-wrapper" style="display:flex;">

     <a href="<%=root_path%>" class="brand-logo"><img src="<%=image_url('logo.svg')%>" alt=""></a>

     <ul  style="flex-grow: 1; margin-left: 48px; " id="nav-mobile" class="hide-on-med-and-down">
       <li class="<%= current_page?(projects_path)  ? "active" : ""%>" ><a href="<%=projects_path%>">Доски</a></li>
       <li class="<%= current_page?(tasks_path)  ? "active" : ""%>"><a href="<%=tasks_path%>">Все задачи</a></li>
       <li class="<%= current_page?(tasks_today_path)  ? "active" : ""%>"><a href="<%=tasks_today_path%>">Сегодня</a></li>
     </ul>

     <ul id="nav-mobile" class=" right hide-on-med-and-down">
       <% if signed_in_user? %>
       <li class="<%= current_page?(points_path)  ? "active" : ""%>" ><a style="display:flex; align-items: center;" href="<%=points_path%>">Бонусы</a></li>
       <li class="" ><a style="display:flex; align-items: center;" href="<%=user_path(current_user)%>"><img style="margin:0; width: 32px; border-radius: 50%;" src="<%=image_url('avatar.jpg')%>" alt=""></a></li>
       <% else %>
       <li><a class="waves-effect waves-light" href="/signin">Войти</a></li>
       <li><a href="/signup">Создать аккаунт</a></li>
       <% end %>
     </ul>
  </div>

 </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

  </head>

<%= render "layouts/navbar" %>

  <script>
      $(document).on('turbolinks:load', function() {
          Waves.displayEffect();
           $('.dropdown-trigger').dropdown();
      });
  </script>

  <body>

    <%= yield %>
  </body>
</html>

<script type="text/javascript">


  function closeTask(id){
    $('#view-task-' + id).remove()

  }

  function makealltodo(ids, type){

    $.ajax({
          url: '/tasks/makealltodo', type: 'post', data: {ids: ids, type: type}, dataType: 'script'
        })
    }

    function makealltoday(ids, type){

      $.ajax({
            url: '/tasks/makealltoday', type: 'post', data: {ids: ids, type: type}, dataType: 'script'
          })
      }

 $(document).on('turbolinks:load', function() {
   <% if signed_in_user?%>
      getNotificationCookie();
  <% end %>
})

  function getNotificationCookie() {
      var myCookie = getCookie("notifications");

      if (myCookie == null) {
        var expires = new Date();
            expires.setHours(23,59,59,999);
          document.cookie = "notifications=true; expires=" + expires.toUTCString();
          $.ajax({ url: '/tasks/notifications', type: 'get' })
      }

}
  function getCookie(name) {
      var dc = document.cookie;
      var prefix = name + "=";
      var begin = dc.indexOf("; " + prefix);
      if (begin == -1) {
          begin = dc.indexOf(prefix);
          if (begin != 0) return null;
      }
      else
      {
          begin += 2;
          var end = document.cookie.indexOf(";", begin);
          if (end == -1) {
          end = dc.length;
          }
      }
      // because unescape has been deprecated, replaced with decodeURI
      //return unescape(dc.substring(begin + prefix.length, end));
      return decodeURI(dc.substring(begin + prefix.length, end));
  }


function taskClick(id) {
  $.ajax({
        url: '/tasks/' + id, type: 'get'
      })
      .done(function(){})
}

function makeToday(id) {
  $.ajax({
        url: '/task/' + id + '/today', type: 'get'
      })
      .done(function(){})
}

function makeDone(id) {
  $.ajax({
        url: '/task/' + id + '/done', type: 'get'
      })
      .done(function(){})
}

function makeTomorrow(id){
  $.ajax({
        url: '/task/' + id + '/todo', type: 'get'
      })
      .done(function(){})
}

function taskUpdateType(id) {

var url = '/task/' + id + '/' + $('#task-select').val();


  $.ajax({
        url: url, type: 'get'
      })
      .done(function(){})
}

  function editTask(id){
    $.ajax({
          url: '/tasks/' + id + '/edit', type: 'get'
        })
        .done(function(){})
  }

  function onHoverTask(id) {
      $('#task-' + id).css("background", "rgba(0, 0, 0, 0.04)")
    }

  function onOutTask(id) {
        $('#task-' + id).css("background", "white")
      }

  function onHoverProject(id) {
          $('#project-btns-' + id).show()
          $('#project-card-' + id).css("background", "rgba(227, 225, 61, 0.52)")
        }

  function onOutProject(id) {
            $('#project-btns-' + id).hide()
            $('#project-card-' + id).css("background", "white")
          }
</script>